# Generated by Django 4.2.4 on 2023-08-04 22:13

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='profile_picture',
            field=models.TextField(max_length=100, null=True, verbose_name='Profile picture'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=apps.users.models.upload_profile_picture_location, verbose_name='Profile picture'),
        ),
    ]
